source: .
baseurl: ''
collections:
  data_sources:
    output: true
    permalink: /data_sources/:path
  partners:
    output: true
    permalink: /integrations/:path
  integrations:
    output: true
    permalink: /integrations/:path
gems:
  - jekyll-redirect-from
